### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/paper-drawer#1]
https://travis-ci.org/Collaborne/paper-drawer/builds/180676136#L1208
```
$ bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git
bower ENORESTARGET  URL sources can't resolve targets
```

**Comment by ankon** [comment]
This is caused by a bug in bower 1.8.0: https://github.com/bower/bower/issues/2391. There is an open PR (https://github.com/bower/bower/pull/2395), but it seems that one is stuck.

The problem is affecting other components, so I'll try to downgrade bower.
